[project]
name = "pw1"
version = "0.1.0"
description = "MachLe PW1 - Let's get started"
readme = "README.md"
authors = [
    { name = "NoeBerdoz" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
]

[tool.uv]
package = false
